# Environment: gcloud_win10 (provider=gcloud)
# Referenced from an experiment as:  environment: ../configs/environments/gcloud_win10.yaml

provider: gcloud
snapshot: cpu-free
project: ${env:GCP_PROJECT}
service_account_key: ${env:GCP_SA_KEY}
instance_prefix: ale
network: agenthle-vpc
subnet: agenthle-vpc
snapshots:
  cpu-free:
    image: ale-win10
    zones:
    - us-central1-a
    - us-central1-b
    - us-east1-b
