# Environment: gcloud_ubuntu (provider=gcloud)
# Referenced from an experiment as:  environment: ../configs/environments/gcloud_ubuntu.yaml

provider: gcloud
snapshot: cpu-free-ubuntu
project: ${env:GCP_PROJECT}
service_account_key: ${env:GCP_SA_KEY}
instance_prefix: ale
network: agenthle-vpc
subnet: agenthle-vpc
snapshots:
  cpu-free-ubuntu:
    image: ale-ubuntu22
    zones:
    - us-central1-a
    - us-east1-b
    - us-west1-a
